version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on 'date'
      - echo Building java
      - cd medicine-stock
      - mvn compile
      - mvn package
      - echo Building the Docker image...
      - docker build -t service/medicinestock .
      - docker tag service/medicinestock $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-medicinestock-registry:medicine-stock
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-medicinestock-registry:medicine-stock
      - echo Writing definitions file
      - printf '[{"name":"medicinestock-service-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-medicinestock-registry:medicine-stock >taskdefinition.json

artifacts:
  files: medicine-stock/taskdefinition.json