version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on 'date'
      - echo Building java
      - cd MedicalRepresentativeScheduleMicroservice
      - mvn compile
      - mvn package
      - echo Building the Docker image...
      - docker build -t service/repscheduleservice .
      - docker tag service/repscheduleservice $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-repscheduleservice-registry:MedicalRepresentativeScheduleMicroservice
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-repscheduleservice-registry:MedicalRepresentativeScheduleMicroservice
      - echo Writing definitions file
      - printf '[{"name":"repschedule-service-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod13-repscheduleservice-registry:MedicalRepresentativeScheduleMicroservice >taskdefinition.json

artifacts:
  files: MedicalRepresentativeScheduleMicroservice/taskdefinition.json